### ISSUE TITLE
Site is hard to use and navigate on mobile

### ISSUE THREAD

**Issue by kerrtravers** [scratchuserstats/scratchstats#15]
On mobile, the site is really hard to use and navigate. I've tried setting the viewport on my fork, but it just squashed everything up.

**Comment by WorldLanguages** [comment]
Hmm. I'll check if in my mobile landscape mode is at least fine. Most of our viewers use PCs.

**Comment by kerrtravers** [comment]
Yeah

**Comment by Sheshank-s** [comment]
I don't think this is something we will implement, sorry
