### ISSUE TITLE
Idea for new API

### ISSUE THREAD

**Issue by AmazingMech2418** [scratchuserstats/scratchstats#16]
You can use the /users/(username) API, use json parsing, and finding parts of the object to use the API. .bio can be used for "about me"s and .status for "what I'm working on"s. I also made a code to follow someone that can be used to remotely follow someone. There could be a "mini profile" in scratchstats!

**Comment by WorldLanguages** [comment]
We only give numbers :P

**Comment by AmazingMech2418** [comment]
OK. XD

**Comment by AmazingMech2418** [comment]
Maybe something for forum totals in each topic, wiki articles, or stats from the Scratch website statistics page...

**Comment by WorldLanguages** [comment]
1) I'm not sure where you can get forum post number
2) We won't give stats for the wiki - we only give for the main site
3) That's already in the global statistics page.
