### ISSUE TITLE
Padding is too large and site doesn't efficiently utilize screen real estate

### ISSUE THREAD

**Issue by ghost** [scratchuserstats/scratchstats#17]

**Comment by ghost** [comment]
I'm ok with @media queries and layout ;P

**Comment by kerrtravers** [comment]
I'm not too good with front-end when it's mixed with back-end. :slightly_frowning_face: 

/cc @GreenBayRules @WorldLanguages

**Comment by ghost** [comment]
What's the difference?

**Comment by kerrtravers** [comment]
I don't know, I'm just more of a front-end guy lol

**Comment by Sheshank-s** [comment]
Lol tbh this sites front end is complete trash, and I might redesign it soon. For now, it's fine though.

**Comment by WorldLanguages** [comment]
@GreenBayRules Why do you say "this site's front end" if there is no back end? 🤔

**Comment by Sheshank-s** [comment]
:P doesn't matter

**Comment by ghost** [comment]
Why was this closed?  It's unresolved, no?
