### ISSUE TITLE
OS Wrong

### ISSUE THREAD

**Issue by kerrtravers** [scratchuserstats/scratchstats#20]
Love the new update! However, I just checked my stats page and it says I'm using Windows NT. I've actually been using OS X since December. Could this just be a caching issue?

**Comment by Sheshank-s** [comment]
Out of anyone I would assume you would know this, but we get the details from Scratch Api. The scratch api can be wrong a lot of times

**Comment by Sheshank-s** [comment]
Sorry accident

**Comment by kerrtravers** [comment]
Yeah, I just haven't seen any cases of this before. I plan to look into how the API more anyway.

**Comment by kerrtravers** [comment]
Fixed in commit 8e2356e333d4c0e761f7c8c9d97e58ee2af3c38a & 12058597052c55ccbe41927dedeca73b4f4344b3.
