### ISSUE TITLE
API

### ISSUE THREAD

**Issue by zspri** [scratchuserstats/scratchstats#22]
Is there any chance that an API will be made from this? Some of the data like most viewed project could be useful.

**Comment by Sheshank-s** [comment]
This is made using the Scratch API lol

**Comment by zspri** [comment]
I know that it uses that, you would have to be redmango not to...
This project uses data that you can't easily get from the API, and it'd be useful instead of going through that mess of index.js.

**Comment by Sheshank-s** [comment]
lol nice
