### ISSUE TITLE
User's country is wrong if it's set to a country code

### ISSUE THREAD

**Issue by SheepTester** [scratchuserstats/scratchstats#23]
A Scratch bug allowed users to set their country to a two-letter country code. ScratchStats seems to perform a search on REST Countries, so it lists whatever country has the two-letter combo in its name or alternate spellings; ScratchStats takes the last item (perhaps to make it work with "United States"?)

To reproduce:
1. change username to that of a user whose country is a two-letter code
2. observe the Miscellaneous section

**Comment by kerrtravers** [comment]
Thanks for reporting this, sorry you didn't get a reply sooner. I've also moved the second bug over to #24 so that we can track both issues separately and work on them faster.

**Comment by WorldLanguages** [comment]
Tracking in #24
