### ISSUE TITLE
Miscellaneous Section Button not working Firefox

### ISSUE THREAD

**Issue by MasterOfTheTiger** [scratchuserstats/scratchstats#30]
When the "white button" is pressed on Firefox, nothing happens. However, when I run `captchaDone()` in the console, it loads correctly. I tried it on Chrome and it works. 

I am using Linux Mint 18.3 and Firefox 58.

**Comment by Sheshank-s** [comment]
I have linux ubuntu lemme see if i can repro

**Comment by Sheshank-s** [comment]
Works  fine for me... Please send a gif and show us how it looks like. I recommend using Peek for Linux

**Comment by MasterOfTheTiger** [comment]
Okay. I will do that when I have a chance. By the way, the button also looked different.

**Comment by WorldLanguages** [comment]
Let me try to repro

**Comment by WorldLanguages** [comment]
Can't repro on Firefox 58.0.1 Windows 10.

Could you provide a screenshot @MasterOfTheTiger

**Comment by WorldLanguages** [comment]
Also does the "load without calculations" link shown when you hold the box appear and work?

**Comment by MasterOfTheTiger** [comment]
Okay, it does not seem to be happening any-more. It works perfectly. To reply to WorldLanguages, no, for some reason it did not show  "load without calculations" as it does in Chrome. Before it actually seemed to be showing it in the box itself.
