### ISSUE TITLE
Spelling issue?

### ISSUE THREAD

**Issue by lholliger** [scratchuserstats/scratchstats#32]
Operative System should be Operating System

(oh and pls add sum more margins)

**Comment by WorldLanguages** [comment]
Oh I forgot about that mistake. In Spanish we say "Sistema Operativo" so that made sense to me. It still makes no sense to me why you would add -ing there, but anyway :P 

Where do you want margins?

**Comment by lholliger** [comment]
mostly on the sides, the bars go nearly to the edge of the screen and i dont believe it looks very good imo. For all i know it'll look worse.

**Comment by kerrtravers** [comment]
The margin looks better when the browser window is bigger, from what I can see. I'll add more padding anyway.

**Comment by kerrtravers** [comment]
Spelling Issue: Fixed in commit fdcc6d74573283c22225e57ea888edcee83209f4.
