### ISSUE TITLE
Average love/view ratio isn't correct

### ISSUE THREAD

**Issue by NilsTheBest** [scratchuserstats/scratchstats#37]
I've noticed that the avg love/view ratio is based on all love/view ratios. Shouldn't it be total loves / total views ratio?

**Comment by WorldLanguages** [comment]
Hi! Please remember the new repo is located here: https://github.com/WorldLanguages/ScratchStats.com
Sadly I can't transfer an issue from an org repo to a personal repo.

**Comment by WorldLanguages** [comment]
To answer your question:
In the old ScratchStats, the love/view ratio was calculated by dividing the amount of loves by the amount of views.
In the new ScratchStats, the love/view ratio is calculated by averaging love/view ratios for each project.

This change was made so all "average" stats are calculated the same way. The old "liking percent" wasn't really an average.
