### ISSUE TITLE
You should add Online or Offline

### ISSUE THREAD

**Issue by DeleteThisAcount** [scratchuserstats/scratchstats#6]
Mabye if the user reading the page has isonline have a box saying if they are online or offline.

**Comment by joker314** [comment]
Hmm, that's a good idea but would require the extension having the ability to read and write to the page (in order for the isOnline servers to verify the account and mark users as bots).

**Comment by DeleteThisAcount** [comment]
true

**Comment by DeleteThisAcount** [comment]
also https://github.com/scratchuserstats/scratchstats/pull/5

**Comment by Sheshank-s** [comment]
Thats not exactly a stat xD Me and @WorldLanguages already discussed this.
